<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>BF1LocalizationTool.Core</AssemblyName>
    <RootNamespace>BF1LocalizationTool.Core</RootNamespace>
  </PropertyGroup>

</Project>
