// =============================================================================
// BF1LocalizationTool.Core — Models/LocalizationEntry.cs
// Автор / Author: EMP_UA (https://github.com/EMP-UA)
// Ліцензія / License: MIT
// =============================================================================

namespace BF1LocalizationTool.Core.Models;

public class LocalizationEntry
{
    // UA: Хеш-ключ рядка (uint32, генерується рушієм)
    // EN: String hash key (uint32, generated by engine)
    public uint Hash { get; init; }

    // UA: Оригінальний текст (читається з вихідної мови)
    // EN: Original text (read from source language)
    public string Original { get; set; } = string.Empty;

    // UA: Перекладений текст. null = не перекладено.
    // EN: Translated text. null = not yet translated.
    public string? Translation { get; set; }

    // UA: Помічено як технічний — не потребує перекладу
    // EN: Marked as technical — does not need translation
    public bool IsTechnical { get; set; }

    // UA: Активний текст: переклад якщо є, інакше оригінал
    // EN: Active text: translation if available, otherwise original
    public string ActiveText => Translation ?? Original;

    // UA: true якщо запис має непорожній переклад
    // EN: true if entry has a non-empty translation
    public bool IsTranslated =>
        !string.IsNullOrWhiteSpace(Translation);

    public string Serialize(bool useTranslation = true) =>
        $"0x{Hash:x8} {(useTranslation ? ActiveText : Original)}";

    public override string ToString() => Serialize();
}
